final class GeneralError implements Exception {
  const GeneralError();
}
